CREATE DATABASE myapp;
USE DATABASE myapp;

CREATE TABLE users(){
     id INT(11) NOT NULL,
     userName VARCHAR(16) NOT NULL,
     password VARCHAR(60) NOT NULL,
     fullName VARCHAR(100) NOT NULL
};

ALTER TABLE users 
     ADD PRIMARY KEY (id);

ALTER TABLE users
     MODIFY id INT(11) NOT NULL 
          AUTO_INCREMENT, AUTO_INCREMENT=2; 

DESCRIBE users;